#                                     

format = """
[ ](bg:#585858)\
$os\
$battery(bg:#CCCC11 fg:#1111CC)\
$username\
[](bg:#444444 fg:#585858)\
$hostname\
[](bg:#0087AF fg:#444444)\
$directory\
[](fg:#0087AF) \
$fill\
$git_branch\
$git_status\
$git_commit\
$nodejs\
$rust\
$localip
$character
"""

# Disable the blank line at the start of the prompt
add_newline = true

[battery]
full_symbol='󰁹'
empty_symbol=''
charging_symbol='󰂄'
discharging_symbol='󰂀'
unknown_symbol='󰂑'
format = '[$symbol$percentage](red) '


[character]
success_symbol = '[>>>](bold green) '
error_symbol = '[✗](bold red) '


# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#585858"
style_root = "bg:#585858"
format = '[$user ]($style)'
disabled = false


# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#585858"
disabled = true # Disabled by default

[fill]
symbol = " "

[hostname]
ssh_only = true
style = "bg:#444444"
ssh_symbol = ''
format = '[$ssh_symbol]($style)[ on ]($style)[$hostname](fg:red bg:$style)'

[directory]
style = "fg:#303030 bg:#0087AF"
read_only = ''
read_only_style="fg:#AF0000 bg:#0087AF"
format = '[ $path ]($style)[$read_only]($read_only_style)'
truncation_length = 5
truncation_symbol = ":"
truncate_to_repo = true
home_symbol = '󰋜'
use_os_path_sep = false

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "


[c]
symbol = " "
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'
[git_branch]
symbol = ""
style = "fg:#303030 bg:#CF9562"
format = '[](fg:#CF9562)[ $symbol $branch ]($style)'

[git_status]
style = "bg:#CF9562 fg:#444444"
conflicted = '󰞇=\($count\)'
ahead = '🏎💨'
behind = '😰'
diverged = '😵'
up_to_date = '✓'
untracked = '🤷'
stashed = '📦=\($count\)'
modified = '📝'
staged = '[s=\($count\)](bg:#CF9562 fg:#444444)'
renamed = '👅'
deleted = '🗑'
format = '[$all_status$ahead_behind ]($style)[](bg:#CF9562 fg:#303030 fg:#444444)'

[git_commit]
style = "bg: #CF9562"
commit_hash_length = 4
tag_symbol = '🔖 '

[localip]
style = "bg:#CF9562 fg:#444444"
ssh_only = false
format = '[$localipv4]($style) '
disabled = false

[memory_usage]
disabled = false
threshold = -1
symbol = ' '
style = "bg:#CF9562 fg:#444444"

[julia]
symbol = " "
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

